In [1]:
import yfinance as yf

In [5]:
df = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "SPY AAPL MSFT",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "7d",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  3 of 3 completed

In [6]:
df

                             AAPL                                     SPY  \
                             Open    High     Low   Close Volume     Open
Datetime
2022-04-13 04:00:00-04:00  169.50  169.50  168.49  168.77    0.0  440.850
2022-04-13 04:01:00-04:00  168.80  168.95  168.80  168.95    0.0  440.760
2022-04-13 04:02:00-04:00  168.95  169.15  168.94  169.04    0.0  441.080
2022-04-13 04:03:00-04:00  169.15  169.24  169.15  169.20    0.0  441.230
2022-04-13 04:04:00-04:00  169.24  169.29  169.00  169.00    0.0  441.190
...                           ...     ...     ...     ...    ...      ...
2022-04-22 19:55:00-04:00  161.46  161.48  161.40  161.47    0.0  424.245
2022-04-22 19:56:00-04:00  161.46  161.50  161.44  161.45    0.0  424.210
2022-04-22 19:57:00-04:00  161.45  161.50  161.45  161.49    0.0  424.220
2022-04-22 19:58:00-04:00  161.49  161.52  161.40  161.50    0.0  424.260
2022-04-22 19:59:00-04:00  161.52  161.52  161.37  161.50    0.0  424.270

                                                            MSFT          \
                             High     Low   Close Volume    Open    High
Datetime
2022-04-13 04:00:00-04:00  440.85  440.05  440.71    0.0  284.29  285.00
2022-04-13 04:01:00-04:00  441.00  440.76  441.00    0.0  284.20  284.40
2022-04-13 04:02:00-04:00  441.20  441.04  441.20    0.0  284.47  284.48
2022-04-13 04:03:00-04:00  441.30  441.23  441.26    0.0  284.45  284.85
2022-04-13 04:04:00-04:00  441.19  441.11  441.14    0.0  284.73  284.88
...                           ...     ...     ...    ...     ...     ...
2022-04-22 19:55:00-04:00  424.25  424.21  424.21    0.0  272.96  273.00
2022-04-22 19:56:00-04:00  424.24  424.21  424.22    0.0  272.96  273.00
2022-04-22 19:57:00-04:00  424.26  424.20  424.26    0.0  272.99  273.00
2022-04-22 19:58:00-04:00  424.31  424.22  424.27    0.0  273.00  273.00
2022-04-22 19:59:00-04:00  424.30  424.22  424.26    0.0  273.00  273.01


                              Low   Close Volume
Datetime
2022-04-13 04:00:00-04:00  283.52  284.05    0.0
2022-04-13 04:01:00-04:00  284.20  284.40    0.0
2022-04-13 04:02:00-04:00  284.20  284.45    0.0
2022-04-13 04:03:00-04:00  284.45  284.70    0.0
2022-04-13 04:04:00-04:00  284.47  284.78    0.0
...                           ...     ...    ...
2022-04-22 19:55:00-04:00  272.95  272.96    0.0
2022-04-22 19:56:00-04:00  272.96  272.99    0.0
2022-04-22 19:57:00-04:00  272.97  273.00    0.0
2022-04-22 19:58:00-04:00  272.99  273.00    0.0
2022-04-22 19:59:00-04:00  272.97  272.99    0.0

[6662 rows x 15 columns]

In [7]:
len(df)

6662

In [8]:
df.shape

(6662, 15)

In [10]:
df.columns

MultiIndex([('AAPL',   'Open'),
            ('AAPL',   'High'),
            ('AAPL',    'Low'),
            ('AAPL',  'Close'),
            ('AAPL', 'Volume'),
            ( 'SPY',   'Open'),
            ( 'SPY',   'High'),
            ( 'SPY',    'Low'),
            ( 'SPY',  'Close'),
            ( 'SPY', 'Volume'),
            ('MSFT',   'Open'),
            ('MSFT',   'High'),
            ('MSFT',    'Low'),
            ('MSFT',  'Close'),
            ('MSFT', 'Volume')],
           )